language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
before_install:
  - gem update bundler
env:
  matrix:
    - SPROCKETS_VERSION="~> 3.3.0"
    - SPROCKETS_VERSION="~> 3.7.0"
    - SPROCKETS_VERSION="~> 4.0.0.beta2"
    - EMBER_SOURCE_VERSION="~> 1.13"
    - EMBER_SOURCE_VERSION="~> 2.6"
    - EMBER_SOURCE_VERSION="~> 2.10"
